project:
  type: website
  output-dir: docs

website:
  title: "David Redek"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: github
        href: https://github.com/davidredek

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

